"use client";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { T } from "@/components/T";

export default function TerminosYCondicionesPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />
      
      <main className="flex-1 pt-40 pb-24">
        <div className="container mx-auto px-6 max-w-4xl animate-fade-in-up">
          <div className="text-center mb-16 border-b border-border pb-10">
            <span className="text-[10px] font-bold tracking-[0.3em] uppercase text-secondary mb-4 block">
              <T>Documento Legal</T>
            </span>
            <h1 className="text-4xl md:text-5xl font-serif text-foreground">
              <T>Términos y Condiciones</T>
            </h1>
          </div>

          <div className="text-sm md:text-base text-muted-foreground font-light leading-relaxed space-y-6">
            
            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>1. Identidad de la empresa</T></h3>
            <p><strong><T>1.1.</T></strong> <T>El presente documento establece los Términos y Condiciones Generales de Contratación (en adelante, las “Condiciones Generales”) que regulan la relación jurídica entre los usuarios (en adelante, el “Usuario” o los “Usuarios”) y GREATDEN, S.A. DE C.V. (en adelante, “MEXTRIPIA”), empresa constituida conforme a las leyes mexicanas.</T></p>
            <p><strong><T>1.2. Datos de identificación:</T></strong></p>
            <ul className="list-disc pl-6 space-y-2">
              <li><T>Razón social: GREATDEN, S.A. DE C.V.</T></li>
              <li><T>Domicilio: Av. Río Consulado Cto Interior 516, Oficina 102, Col. Tlatilco, Alcaldía Azcapotzalco, C.P. 02860, Ciudad de México.</T></li>
              <li><T>Correo electrónico de contacto: atencion@mextripia.com</T></li>
              <li><T>Sitio web y plataformas asociadas: los dominios, micrositios, portales o herramientas digitales utilizadas para la promoción y contratación de Servicios.</T></li>
            </ul>
            <p><T>MEXTRIPIA se dedica a la conceptualización, organización y gestión de experiencias gastronómicas, culturales, turísticas, de entretenimiento y de activación de marca. Al contratar cualquier servicio, realizar una solicitud de reservación o efectuar un pago, el Usuario acepta expresamente las presentes Condiciones Generales.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>2. Objeto y alcance de los servicios</T></h3>
            <p><strong><T>2.1.</T></strong> <T>Los Servicios ofrecidos por MEXTRIPIA incluyen, sin limitarse a:</T></p>
            <ul className="list-disc pl-6 space-y-2">
              <li><T>Experiencias gastronómicas y culturales: tours culinarios, clases de cocina, catas, fiestas temáticas, recorridos guiados y actividades inmersivas en diferentes destinos de México.</T></li>
              <li><T>Activaciones y eventos de marca: diseño conceptual, producción, logística, ambientación y gestión de experiencias para empresas y clientes corporativos.</T></li>
              <li><T>Servicios turísticos complementarios: transporte opcional, coordinación logística, reservas de restaurantes, entradas a espectáculos y servicios de hospitalidad.</T></li>
              <li><T>Servicios adicionales relacionados con el Mundial 2026: reservaciones en restaurantes y bares, acceso a fan zones (Básica, Gastronómica y VIP Experiencial), actividades temáticas y experiencias de hospitalidad.</T></li>
            </ul>
            <p><strong><T>2.2.</T></strong> <T>Cada Servicio contará con una descripción detallada en la plataforma digital de MEXTRIPIA o en la propuesta enviada al cliente, especificando: duración, lugar de encuentro, características, entregables, restricciones, disponibilidad y condiciones particulares.</T></p>
            <p><strong><T>2.3.</T></strong> <T>MEXTRIPIA se reserva el derecho de modificar, sustituir o actualizar el catálogo de Servicios en cualquier momento, sin necesidad de aviso previo, garantizando siempre el cumplimiento de las contrataciones confirmadas.</T></p>
            <p><strong><T>2.4.</T></strong> <T>El Usuario reconoce que los Servicios podrán depender de proveedores externos, y que las políticas internas de dichos terceros (restaurantes, bares, recintos, transportistas, guías, artistas, etc.) serán aplicables y vinculantes.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>3. Proceso de contratación</T></h3>
            <p><strong><T>3.1. Medios habilitados para contratar.</T></strong> <T>La contratación de los Servicios ofrecidos por MEXTRIPIA únicamente podrá realizarse a través de los siguientes canales oficiales:</T></p>
            <ul className="list-disc pl-6 space-y-2">
              <li><T>El sitio web y plataformas digitales propiedad de MEXTRIPIA o gestionadas directamente por ésta.</T></li>
              <li><T>Solicitudes enviadas por correo electrónico al contacto oficial de MEXTRIPIA.</T></li>
              <li><T>Otros canales expresamente autorizados por MEXTRIPIA (por ejemplo, acuerdos corporativos, agentes acreditados, convenios con empresas o colaboradores externos).</T></li>
            </ul>
            <p><T>Queda expresamente prohibida la contratación de Servicios a través de intermediarios no autorizados, páginas web apócrifas, revendedores o canales no reconocidos por MEXTRIPIA. En tales casos, MEXTRIPIA no asumirá responsabilidad alguna frente al Usuario.</T></p>
            
            <p><strong><T>3.2. Obligaciones del Usuario al contratar.</T></strong> <T>El Usuario se compromete a proporcionar, en el momento de la contratación, información veraz, completa, actualizada y suficiente para la correcta gestión del Servicio. Esto incluye, sin limitarse a:</T></p>
            <ul className="list-disc pl-6 space-y-2">
              <li><T>Nombre(s) y apellidos completos.</T></li>
              <li><T>Datos de contacto (correo electrónico, número telefónico y, en su caso, WhatsApp).</T></li>
              <li><T>Fecha, horario y destino de interés.</T></li>
              <li><T>Número de participantes, especificando si son adultos, menores de edad o personas con necesidades especiales.</T></li>
              <li><T>Requerimientos adicionales (alimenticios, médicos, logísticos, accesibilidad, etc.).</T></li>
              <li><T>Datos fiscales en caso de requerir factura.</T></li>
            </ul>
            <p><T>El Usuario será responsable de cualquier error, omisión o falsedad en los datos proporcionados. MEXTRIPIA no será responsable por cancelaciones, rechazos de reserva, imposibilidad de acceso a experiencias o cargos adicionales ocasionados por información incorrecta o incompleta.</T></p>
            
            <p><strong><T>3.3. Condiciones para la validez de la contratación.</T></strong> <T>Toda contratación de Servicios estará siempre sujeta al cumplimiento acumulativo de los siguientes elementos:</T></p>
            <ul className="list-disc pl-6 space-y-2">
              <li><T>Confirmación de disponibilidad del servicio, fecha, lugar o proveedor por parte de MEXTRIPIA.</T></li>
              <li><T>Asignación de un número de reservación único e intransferible, que identificará la contratación.</T></li>
              <li><T>Pago íntegro o parcial del precio del Servicio, conforme a las condiciones particulares indicadas (ej. apartado no reembolsable, pago total anticipado, saldo pendiente a liquidar en fecha determinada).</T></li>
            </ul>
            <p><T>Sin estos tres elementos, la contratación se considerará incompleta y no generará obligaciones para MEXTRIPIA.</T></p>

            <p><strong><T>3.4. Proceso de validación.</T></strong> <T>Una vez recibido el pago y confirmada la disponibilidad, MEXTRIPIA enviará al correo electrónico proporcionado por el Usuario un documento de confirmación de reserva, en el que constará:</T></p>
            <ul className="list-disc pl-6 space-y-2">
              <li><T>Número de reservación.</T></li>
              <li><T>Detalles del servicio contratado (fecha, hora, punto de encuentro, características principales).</T></li>
              <li><T>Nombre del titular de la reserva y número de participantes.</T></li>
              <li><T>Condiciones particulares y restricciones aplicables.</T></li>
            </ul>
            <p><T>En caso de que no se emita dicha confirmación, el Usuario deberá considerarse como no contratado el Servicio, aun cuando hubiese realizado el pago. MEXTRIPIA se compromete, en tal caso, a gestionar de inmediato la devolución correspondiente.</T></p>

            <p><strong><T>3.5. Carácter personal de la contratación.</T></strong> <T>Las contrataciones realizadas son personales e intransferibles, salvo autorización expresa de MEXTRIPIA. Queda prohibida la cesión, reventa, comercialización o transmisión de reservas sin autorización.</T></p>

            <p><strong><T>3.6. Prevención de fraudes.</T></strong> <T>MEXTRIPIA se reserva el derecho de rechazar o cancelar cualquier contratación en la que existan indicios de: Información falsa o incompleta proporcionada por el Usuario; Pagos no reconocidos, sospecha de fraude bancario, clonación de tarjetas o contracargos; Revendedores no autorizados o usos indebidos de la marca MEXTRIPIA.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>4. Reservaciones</T></h3>
            <p><strong><T>4.1. Solicitud de reservación.</T></strong> <T>Para solicitar un Servicio, el Usuario deberá enviar una solicitud de reservación a través de los medios habilitados por MEXTRIPIA, los cuales podrán incluir: Formularios disponibles en el sitio web oficial; Correos electrónicos dirigidos a las cuentas oficiales de MEXTRIPIA.</T></p>
            <p><strong><T>4.2. Carácter no vinculante de la solicitud.</T></strong> <T>La solicitud de reservación no implica confirmación automática del Servicio. Dicha solicitud será considerada únicamente como una petición sujeta a validación de disponibilidad, condiciones particulares, capacidad de aforo y pago del anticipo o totalidad del precio según corresponda.</T></p>
            <p><strong><T>4.3. Condiciones para la confirmación.</T></strong> <T>La reservación se considerará válida, vinculante y confirmada únicamente cuando se cumplan de manera acumulativa las siguientes condiciones: El Usuario reciba de MEXTRIPIA un número de reservación único, personal e intransferible; El pago requerido (total o parcial, según el caso) haya sido procesado y confirmado por los sistemas de pago autorizados; El Usuario haya recibido un correo electrónico de confirmación con los detalles de la experiencia. Hasta que no concurran estos tres requisitos, la contratación se considerará incompleta y MEXTRIPIA no asumirá ninguna obligación frente al Usuario.</T></p>
            <p><strong><T>4.4. Contenido de la confirmación.</T></strong> <T>El documento de confirmación de la reservación contendrá, al menos, la siguiente información: Fecha y hora del Servicio; Lugar o punto de encuentro; Número de participantes incluidos en la reservación; Condiciones particulares aplicables al Servicio; Restricciones, recomendaciones y requisitos específicos (ejemplo: código de vestimenta, edad mínima, documentos de identificación, puntualidad); Instrucciones adicionales necesarias para el correcto disfrute del Servicio.</T></p>
            <p><strong><T>4.5. Imposibilidad de confirmación.</T></strong> <T>En caso de que, por cualquier motivo, un Servicio no pueda confirmarse en la fecha, horario o condiciones solicitadas, MEXTRIPIA podrá: Ofrecer al Usuario alternativas razonables, incluyendo cambio de fecha, de horario, de proveedor o de experiencia similar; Reembolsar el importe pagado por el Usuario, conforme a la política de cancelaciones aplicable. La aceptación de las alternativas será siempre a discreción del Usuario. En caso de rechazo, únicamente procederá el reembolso conforme a los términos aquí establecidos.</T></p>
            <p><strong><T>4.6. Disponibilidad y políticas de proveedores.</T></strong> <T>Todas las reservaciones estarán sujetas a la disponibilidad real del Servicio y a las políticas internas de cada establecimiento, proveedor, restaurante, bar, guía, transportista o artista involucrado. Dichas políticas podrán incluir, entre otros: Horarios de operación; Capacidad máxima de aforo; Restricciones de edad, salud, seguridad o accesibilidad; Normas de vestimenta o conducta; Reglas de consumo y permanencia en el recinto. El Usuario acepta que estas políticas de proveedores son vinculantes y forman parte integral de su contratación.</T></p>
            <p><strong><T>4.7. Carácter personal e intransferible de la reservación.</T></strong> <T>Cada reservación emitida es personal, nominativa e intransferible. Cualquier cesión, reventa o modificación no autorizada expresamente por MEXTRIPIA carecerá de validez y podrá implicar la cancelación de la misma sin derecho a reembolso.</T></p>
            <p><strong><T>4.8. Obligación de puntualidad.</T></strong> <T>El Usuario deberá presentarse en el lugar y hora señalados en la confirmación de reservación. La falta de puntualidad podrá implicar la pérdida total del Servicio sin derecho a reembolso ni reprogramación.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>5. Servicios adicionales – Mundial 2026</T></h3>
            <p><strong><T>5.1. Gestión de reservaciones en restaurantes y bares.</T></strong> <T>Durante el periodo comprendido del 11 de junio al 19 de julio de 2026 (Copa Mundial de la FIFA 2026), MEXTRIPIA ofrecerá al Usuario la posibilidad de gestionar reservaciones en restaurantes y bares reconocidos de la Ciudad de México, con el fin de que puedan disfrutar de la transmisión en vivo de los partidos en un ambiente controlado, temático y acompañado de servicios de hospitalidad. Las reservaciones estarán sujetas a la disponibilidad de cada establecimiento, a sus políticas internas y a los términos y condiciones específicos de cada recinto, que el Usuario acepta en el momento de la contratación.</T></p>
            <p><strong><T>5.2. Consumo de alimentos y bebidas.</T></strong> <T>El consumo de alimentos, bebidas y otros servicios adicionales (propinas, extras, pedidos especiales) no está incluido en la reservación inicial, salvo que expresamente se indique lo contrario en la descripción del paquete contratado. El pago de consumos adicionales será responsabilidad directa del Usuario frente al establecimiento. El incumplimiento de estas obligaciones podrá derivar en la cancelación del acceso o en cargos adicionales que serán responsabilidad exclusiva del Usuario.</T></p>
            <p><strong><T>5.3. Modalidades de Fan Zone.</T></strong> <T>MEXTRIPIA pondrá a disposición del Usuario accesos a Fan Zones temáticas, ofrecidas en tres modalidades:</T></p>
            <ul className="list-disc pl-6 space-y-2">
              <li><T>Fan Zone Básica: acceso a pantallas gigantes de transmisión en vivo, zonas de asientos o puffs, decoración futbolera temática, mini canchas para actividades recreativas (ej. penales o retas rápidas 3v3) y photobooth con accesorios mundialistas.</T></li>
              <li><T>Fan Zone Gastronómica: incluye todo lo señalado en la modalidad Básica, más áreas de food trucks y barras de snacks con gastronomía mexicana e internacional, coctelería temática inspirada en países participantes y maridaje con cervezas artesanales, tequilas o mezcales.</T></li>
              <li><T>Fan Zone VIP Experiencial: incluye lo anterior, más acceso a una zona lounge premium con mobiliario exclusivo, servicio personalizado de meseros, meet & greet con exfutbolistas o comentaristas deportivos (sujeto a disponibilidad y presupuesto), así como DJ o música en vivo antes y después de los partidos.</T></li>
            </ul>
            <p><T>El contenido exacto de cada Fan Zone podrá variar en función de los acuerdos con proveedores, disponibilidad de artistas y condiciones logísticas de cada evento.</T></p>
            <p><strong><T>5.4. Condiciones generales aplicables a las experiencias.</T></strong> <T>Las experiencias vinculadas al Mundial 2026 estarán sujetas, sin limitarse, a los siguientes factores: Disponibilidad de espacios y aforo máximo, en cumplimiento con las disposiciones legales y de protección civil vigentes en cada momento; Disponibilidad de artistas invitados, comentaristas o proveedores, quienes podrán ser sustituidos, modificados o cancelados por causas ajenas a MEXTRIPIA; Cambios de horarios oficiales de partidos y transmisiones, derivados de la programación deportiva global; Restricciones de seguridad o sanitarias que pudieran imponer autoridades locales, recintos o proveedores.</T></p>
            <p><strong><T>5.5. Exclusión de responsabilidad.</T></strong> <T>MEXTRIPIA no será responsable frente al Usuario por: Modificaciones, retrasos o cancelaciones en la programación oficial de los partidos de la Copa Mundial 2026; Decisiones operativas adoptadas por los establecimientos aliados (cambios de mesa, limitaciones de consumo, restricciones de acceso, normas de conducta, etc.); Causas de fuerza mayor o caso fortuito, incluyendo, sin limitarse, a condiciones climáticas, fallos en transmisiones satelitales, disposiciones gubernamentales o sanitarias.</T></p>
            <p><strong><T>5.6. Confirmación y pago de reservación.</T></strong> <T>El Usuario reconoce que su acceso a las experiencias adicionales del Mundial 2026 quedará confirmado únicamente cuando: Reciba un número de reservación emitido por MEXTRIPIA; Realice el pago de la reservación, ingresando dicho número y el monto indicado en la plataforma de pago habilitada; Obtenga un correo electrónico de confirmación que detalle fecha, lugar, modalidad de Fan Zone o restaurante asignado y número de participantes. El pago de la reservación podrá ser no reembolsable, conforme a las políticas de cada proveedor y a lo establecido en el apartado de cancelaciones y reembolsos.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>6. Pagos</T></h3>
            <p><strong><T>6.1. Moneda e impuestos aplicables.</T></strong> <T>Todos los precios publicados estarán expresados en pesos mexicanos (MXN), salvo indicación en contrario, e incluirán los impuestos aplicables conforme a la legislación fiscal vigente. En caso de cotizar en otra moneda, el cargo final se realizará en pesos mexicanos al tipo de cambio aplicable en la fecha de liquidación. El Usuario será responsable de cualquier comisión bancaria, cargo por tipo de cambio o tarifa adicional impuesta por su institución financiera.</T></p>
            <p><strong><T>6.2. Métodos de pago autorizados.</T></strong> <T>El Usuario podrá realizar los pagos exclusivamente mediante los métodos electrónicos autorizados en el portal de MEXTRIPIA, que podrán incluir: Tarjetas de crédito y débito; Plataformas de pago electrónico o billeteras digitales que se encuentren expresamente habilitadas en el sistema de MEXTRIPIA. Queda prohibido efectuar pagos a cuentas o enlaces no oficiales. MEXTRIPIA no será responsable por pagos realizados a terceros no autorizados.</T></p>
            <p><strong><T>6.3. Confirmación del pago y validación de reservación.</T></strong> <T>Para confirmar su lugar en un Servicio, el Usuario deberá: Ingresar su número de reservación en la plataforma de pago habilitada; Liquidar el monto correspondiente conforme a lo indicado en la confirmación de reservación; Esperar la validación electrónica de la operación. El Servicio se considerará asegurado únicamente cuando el pago haya sido efectivamente acreditado y confirmado por MEXTRIPIA.</T></p>
            <p><strong><T>6.4. Comprobantes y facturación.</T></strong> <T>Una vez procesado el pago, el Usuario recibirá en el correo registrado: Confirmación electrónica de la reserva; Comprobante de pago emitido por la pasarela correspondiente. En caso de requerir factura fiscal (CFDI), el Usuario deberá solicitarla al momento de la contratación, proporcionando datos fiscales correctos y completos. MEXTRIPIA no será responsable por errores en la facturación derivados de datos incorrectos proporcionados por el Usuario ni podrá reexpedir comprobantes fuera de los plazos legales.</T></p>
            <p><strong><T>6.5. Rechazos, contracargos y falta de acreditación.</T></strong> <T>En los siguientes supuestos, la reservación quedará automáticamente cancelada sin responsabilidad para MEXTRIPIA: Rechazo de la transacción por parte de la institución emisora del medio de pago; Falta de acreditación del pago dentro de los plazos señalados; Detección de operaciones sospechosas de fraude, clonación de tarjetas, suplantación de identidad o contracargos iniciados por el Usuario. En caso de contracargos, MEXTRIPIA se reserva el derecho de reclamar judicial o extrajudicialmente los importes correspondientes, así como los gastos administrativos y legales derivados.</T></p>
            <p><strong><T>6.6. Pagos parciales, anticipos y no reembolsabilidad.</T></strong> <T>Dependiendo del Servicio, podrá requerirse: Pago total anticipado: para confirmar la reserva; Pago parcial o anticipo no reembolsable: como apartado para asegurar disponibilidad; Saldo pendiente: a liquidarse en la fecha y forma indicada en la confirmación. En caso de que el Usuario no liquide el saldo en los tiempos previstos, la reservación podrá ser cancelada, perdiendo el anticipo no reembolsable.</T></p>
            <p><strong><T>6.7. Seguridad en transacciones.</T></strong> <T>Todas las operaciones realizadas a través de los portales de pago de MEXTRIPIA estarán encriptadas y protegidas por certificados de seguridad SSL y sistemas antifraude. Sin embargo, el Usuario reconoce que ninguna transmisión electrónica está totalmente libre de riesgos y exime a MEXTRIPIA de responsabilidad por vulneraciones derivadas de actos de terceros ajenos a su control.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>7. Cancelaciones, modificaciones y reembolsos</T></h3>
            <p><strong><T>7.1. Solicitud de cancelación o modificación.</T></strong> <T>El Usuario podrá solicitar la modificación o cancelación de su reservación enviando un correo electrónico a la dirección oficial de contacto de MEXTRIPIA (atencion@mextripia.com), indicando de forma clara: Número de reservación; Nombre completo del titular de la reserva; Servicio contratado; Fecha prevista del Servicio; Motivo de la cancelación o modificación solicitada.</T></p>
            <p><strong><T>7.2. Condiciones de aceptación.</T></strong> <T>Las solicitudes estarán sujetas a las siguientes condiciones: Antelación con que se realicen: dependiendo de la naturaleza del Servicio, el plazo mínimo de preaviso podrá ser de 7 días naturales (para experiencias generales), 3 días naturales (para experiencias gastronómicas específicas) o 1 día natural (para experiencias de consumo inmediato o bajo aforo limitado); Políticas particulares del proveedor o establecimiento: cada restaurante, bar, recinto o proveedor podrá aplicar sus propias reglas en materia de cancelaciones, modificaciones y reembolsos; Disponibilidad en la nueva fecha solicitada: la reprogramación quedará siempre condicionada a la capacidad del proveedor para aceptar cambios. El Usuario reconoce que en algunos casos las solicitudes realizadas fuera de los plazos establecidos no podrán ser atendidas, lo que implicará la pérdida total del importe abonado.</T></p>
            <p><strong><T>7.3. Gestión por parte de MEXTRIPIA.</T></strong> <T>En los casos en que proceda, MEXTRIPIA actuará como intermediario para gestionar ante el proveedor la modificación, reprogramación o, en su caso, el reembolso parcial o total del servicio contratado. La aceptación final de la cancelación o modificación dependerá siempre de las políticas del proveedor. MEXTRIPIA se compromete a comunicar al Usuario, en un plazo razonable, la resolución adoptada por el proveedor.</T></p>
            <p><strong><T>7.4. Servicios no reembolsables.</T></strong> <T>Existen servicios, anticipos o apartados que podrán ser no reembolsables, lo cual será informado al Usuario antes de la confirmación de la contratación. Ejemplos: Reservaciones en fechas de alta demanda (ej. partidos del Mundial 2026, eventos especiales, festividades nacionales); Servicios con cupo limitado o con pago de artistas, guías o recintos por anticipado; Anticipos destinados a asegurar disponibilidad. En estos casos, la cancelación por parte del Usuario no dará lugar a devolución alguna, independientemente de la causa invocada.</T></p>
            <p><strong><T>7.5. Forma de reembolso.</T></strong> <T>Cuando proceda, los reembolsos se realizarán utilizando el mismo método de pago empleado por el Usuario. Si por razones técnicas no fuera posible, MEXTRIPIA podrá efectuar la devolución mediante transferencia bancaria a una cuenta a nombre del titular original de la reservación. El monto reembolsado corresponderá únicamente al importe efectivamente pagado por el Usuario a MEXTRIPIA, sin incluir gastos financieros, comisiones bancarias ni costos adicionales asumidos por el Usuario.</T></p>
            <p><strong><T>7.6. Plazos de acreditación.</T></strong> <T>Los tiempos de acreditación del reembolso dependerán de los plazos establecidos por las instituciones financieras, pudiendo extenderse entre 5 y 20 días hábiles contados a partir de la confirmación de procedencia del reembolso.</T></p>
            <p><strong><T>7.7. Limitación de responsabilidad.</T></strong> <T>El Usuario reconoce y acepta que: MEXTRIPIA no podrá garantizar devoluciones cuando los proveedores determinen que no procede el reembolso; MEXTRIPIA no será responsable de los retrasos imputables a instituciones financieras o pasarelas de pago; En ningún caso se devolverán importes correspondientes a consumos adicionales, propinas, gastos de transporte u otros servicios no contratados directamente con MEXTRIPIA.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>8. Obligaciones del Usuario</T></h3>
            <p><T>El Usuario, al contratar y utilizar los Servicios de MEXTRIPIA, acepta de manera expresa las siguientes obligaciones:</T></p>
            <p><strong><T>8.1. Veracidad y exactitud de la información.</T></strong> <T>Proporcionar datos veraces, completos, exactos y actualizados en todo momento. Notificar de inmediato cualquier error u omisión detectado en los datos enviados a MEXTRIPIA. Reconocer que cualquier inexactitud, falsedad u omisión será responsabilidad exclusiva del Usuario y podrá derivar en la cancelación del Servicio sin derecho a reembolso.</T></p>
            <p><strong><T>8.2. Cumplimiento de requisitos específicos.</T></strong> <T>Acreditar, cuando aplique, los requisitos de edad mínima, documentación (INE, pasaporte, visa, comprobantes médicos, certificados de vacunación, etc.) o condiciones de seguridad exigidas para el Servicio contratado. Seguir las instrucciones, restricciones y recomendaciones indicadas por MEXTRIPIA o por los proveedores durante la experiencia. En caso de menores de edad, garantizar que estos participen bajo la supervisión directa de un adulto responsable.</T></p>
            <p><strong><T>8.3. Respeto de políticas y normas de convivencia.</T></strong> <T>Respetar las políticas de conducta, higiene, vestimenta, seguridad, convivencia y puntualidad establecidas por MEXTRIPIA, por los proveedores, restaurantes, bares, venues o recintos contratados. Abstenerse de conductas inapropiadas, agresivas, discriminatorias o que alteren el orden y la seguridad del evento. Cumplir con las normas sanitarias, de protección civil y de seguridad dictadas por autoridades o proveedores. El incumplimiento de estas políticas facultará a MEXTRIPIA o al proveedor a negar el acceso, retirar al Usuario del evento o cancelar la prestación del Servicio, sin obligación de reembolso.</T></p>
            <p><strong><T>8.4. Responsabilidad sobre gastos adicionales.</T></strong> <T>Asumir íntegramente los costos de transporte hacia y desde el punto de encuentro, salvo que el mismo esté expresamente incluido en el paquete. Cubrir propinas, consumos adicionales, bebidas, alimentos, souvenirs u otros gastos no contemplados en la contratación inicial. Reconocer que estos gastos no son responsabilidad de MEXTRIPIA.</T></p>
            <p><strong><T>8.5. Prohibición de reventa o cesión no autorizada.</T></strong> <T>No revender, transferir, ceder ni comercializar las reservaciones sin autorización previa y expresa de MEXTRIPIA. Reconocer que cualquier intento de reventa o cesión no autorizada invalidará la reservación de forma automática, sin derecho a reembolso.</T></p>
            <p><strong><T>8.6. Consumo responsable de alcohol y sustancias.</T></strong> <T>En experiencias donde se incluya consumo de bebidas alcohólicas (ej. catas, fan zones, tours gastronómicos), hacerlo de manera responsable y conforme a las leyes locales. Queda prohibido el consumo de drogas, estupefacientes o sustancias ilegales en todos los Servicios gestionados por MEXTRIPIA. El incumplimiento facultará a MEXTRIPIA o al proveedor a negar el acceso o retirar al Usuario del evento sin derecho a reembolso.</T></p>
            <p><strong><T>8.7. Puntualidad y asistencia.</T></strong> <T>Presentarse puntualmente en el lugar, fecha y hora indicados en la confirmación de reservación. Reconocer que los Servicios tienen un tiempo de inicio fijo y que la impuntualidad podrá implicar la pérdida parcial o total de la experiencia sin derecho a reembolso.</T></p>
            <p><strong><T>8.8. Daños y responsabilidad personal.</T></strong> <T>Cuidar y hacer uso adecuado de las instalaciones, mobiliario, equipos, transportes, materiales y objetos puestos a disposición durante la experiencia. Responder económicamente por los daños ocasionados de manera dolosa o negligente a terceros, instalaciones, mobiliario o equipo utilizado en la experiencia.</T></p>
            <p><strong><T>8.9. Aceptación de consecuencias por incumplimiento.</T></strong> <T>El incumplimiento por parte del Usuario de cualquiera de las obligaciones aquí previstas facultará a MEXTRIPIA y/o a los proveedores a: Cancelar el Servicio contratado sin derecho a reembolso; Negar el acceso al evento o experiencia; Solicitar la reparación de daños y perjuicios ocasionados; Ejercer las acciones legales correspondientes para proteger sus derechos.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>9. Limitación de responsabilidad</T></h3>
            <p><strong><T>9.1. Naturaleza de la intervención de MEXTRIPIA.</T></strong> <T>El Usuario reconoce y acepta que MEXTRIPIA actúa como gestor, organizador y en muchos casos como intermediario entre el Usuario y proveedores externos de servicios (restaurantes, bares, venues, guías, transportistas, artistas, recintos turísticos, entre otros). Por tanto, la correcta ejecución de ciertos servicios depende directamente de dichos proveedores, cuyas políticas internas resultan vinculantes para el Usuario.</T></p>
            <p><strong><T>9.2. Exclusiones de responsabilidad.</T></strong> <T>MEXTRIPIA no será responsable, en ningún caso, por: Cancelaciones, retrasos, fallas o deficiencias imputables a proveedores externos contratados para la ejecución parcial o total del Servicio; Condiciones climáticas adversas, fenómenos naturales, eventos de fuerza mayor o caso fortuito que afecten la ejecución del Servicio; Situaciones sanitarias, restricciones gubernamentales o medidas de seguridad pública que impidan o limiten el desarrollo del Servicio; Pérdida, robo o daño de pertenencias personales del Usuario antes, durante o después del Servicio; Accidentes, lesiones, enfermedades o daños ocasionados por la negligencia, imprudencia, incumplimiento de instrucciones o estado de salud del Usuario; Daños indirectos, pérdidas de oportunidad, expectativas de negocio, ingresos futuros, gastos colaterales o cualquier forma de lucro cesante.</T></p>
            <p><strong><T>9.3. Riesgos asumidos por el Usuario.</T></strong> <T>El Usuario reconoce y acepta que la participación en experiencias gastronómicas, culturales, de entretenimiento o eventos deportivos conlleva ciertos riesgos inherentes, entre los que se incluyen, de manera enunciativa mas no limitativa: Riesgos alimenticios (alergias, intolerancias, intoxicaciones); Riesgos físicos (caídas, lesiones menores o mayores en actividades recreativas, deportivas o de transporte); Riesgos asociados al consumo de bebidas alcohólicas; Riesgos de interacción con multitudes o eventos masivos. El Usuario declara ser consciente de estos riesgos, y asume plena responsabilidad sobre su participación en las experiencias contratadas.</T></p>
            <p><strong><T>9.4. Limitación cuantitativa de responsabilidad.</T></strong> <T>En cualquier caso, la responsabilidad máxima de MEXTRIPIA frente al Usuario se limitará estrictamente al monto efectivamente pagado por el Usuario por el Servicio específico contratado que haya dado origen a la reclamación. En ningún caso procederán indemnizaciones por montos superiores, daños punitivos ni compensaciones adicionales. Si la reclamación involucrara a un tercero proveedor, la eventual responsabilidad quedará sujeta a las políticas y limitaciones legales de dicho proveedor.</T></p>
            <p><strong><T>9.5. Exoneración en caso de incumplimiento del Usuario.</T></strong> <T>MEXTRIPIA no será responsable por el incumplimiento, total o parcial, del Servicio cuando éste derive de: La falta de puntualidad del Usuario; El incumplimiento de requisitos de acceso (documentación, edad mínima, vestimenta); La omisión de restricciones médicas, sanitarias o de seguridad notificadas previamente; Conductas inadecuadas, negligentes o ilícitas por parte del Usuario o sus acompañantes.</T></p>
            <p><strong><T>9.6. Indemnidad.</T></strong> <T>El Usuario se obliga a sacar en paz y a salvo a MEXTRIPIA de cualquier reclamación, demanda, procedimiento o acción judicial interpuesta por terceros derivada de actos u omisiones del propio Usuario durante la ejecución del Servicio.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>10. Propiedad intelectual</T></h3>
            <p><strong><T>10.1. Titularidad de derechos.</T></strong> <T>Todos los contenidos disponibles en los sitios, plataformas y materiales promocionales de MEXTRIPIA —incluyendo, sin limitación, textos, descripciones de servicios, material gráfico, logotipos, marcas registradas, nombres comerciales, fotografías, imágenes, audios, videos, diseños, iconos, interfaces, códigos fuente y cualquier otro elemento protegido por derechos de propiedad intelectual o industrial— son propiedad exclusiva de GREATDEN, S.A. DE C.V. o de terceros licenciantes que han autorizado su uso.</T></p>
            <p><strong><T>10.2. Protección legal.</T></strong> <T>Dichos contenidos se encuentran protegidos por la legislación nacional e internacional en materia de derechos de autor, propiedad industrial y propiedad intelectual, incluyendo, de manera enunciativa mas no limitativa: La Ley Federal del Derecho de Autor de México; La Ley de la Propiedad Industrial de México; Tratados internacionales suscritos por los Estados Unidos Mexicanos, tales como el Convenio de Berna, ADPIC (TRIPS) y tratados de la OMPI.</T></p>
            <p><strong><T>10.3. Licencia de uso limitada.</T></strong> <T>El acceso al sitio web y a los materiales de MEXTRIPIA no concede al Usuario derecho alguno de explotación sobre los contenidos, salvo una licencia de uso personal, limitada, no exclusiva, revocable y no transferible, cuyo único fin es permitir la correcta contratación y disfrute de los servicios.</T></p>
            <p><strong><T>10.4. Usos prohibidos.</T></strong> <T>Queda estrictamente prohibido, sin autorización previa y por escrito de MEXTRIPIA: Reproducir, copiar, distribuir, comunicar públicamente, transformar, modificar, traducir, adaptar, descompilar, extraer o utilizar con fines comerciales o promocionales los contenidos protegidos; Utilizar logotipos, nombres comerciales, marcas o signos distintivos de MEXTRIPIA para fines publicitarios, comerciales o de asociación sin consentimiento expreso; Generar obras derivadas, sitios espejo, reventa de contenidos, scraping o extracción de bases de datos pertenecientes a MEXTRIPIA.</T></p>
            <p><strong><T>10.5. Contenidos de terceros y licencias.</T></strong> <T>En caso de que algunos contenidos, fotografías, imágenes, videos o materiales pertenecieran a terceros y se utilicen bajo licencias, cesiones o autorizaciones, dichos derechos corresponderán a sus respectivos titulares. El Usuario se obliga a respetar íntegramente tales derechos y a no realizar actos que vulneren su protección legal.</T></p>
            <p><strong><T>10.6. Infracciones.</T></strong> <T>Cualquier uso no autorizado de los contenidos propiedad de MEXTRIPIA o de sus licenciantes constituirá una infracción a los derechos de propiedad intelectual e industrial, pudiendo dar lugar a: La exigencia de responsabilidad civil por daños y perjuicios; El ejercicio de acciones legales civiles, administrativas y/o penales conforme a la legislación aplicable; La suspensión inmediata de los accesos o servicios contratados, sin obligación de reembolso.</T></p>
            <p><strong><T>10.7. Colaboraciones y cesión de contenidos.</T></strong> <T>En caso de que un Usuario participe en actividades de co-creación de contenido (ejemplo: fotografías, testimonios, grabaciones en tours o fan zones), éste concede a MEXTRIPIA, de forma gratuita, una licencia no exclusiva, transferible, sublicenciable, mundial y por tiempo indefinido para usar, reproducir, comunicar públicamente, distribuir y transformar dicho contenido, única y exclusivamente con fines promocionales, comerciales o publicitarios relacionados con los servicios de MEXTRIPIA.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>11. Legislación aplicable y jurisdicción</T></h3>
            <p><strong><T>11.1.</T></strong> <T>Las presentes Condiciones Generales se regirán por las leyes de los Estados Unidos Mexicanos.</T></p>
            <p><strong><T>11.2.</T></strong> <T>Para cualquier controversia derivada de la interpretación o ejecución de estas Condiciones, las partes se someten a los tribunales competentes de la Ciudad de México, renunciando expresamente a cualquier otro fuero que pudiera corresponderles.</T></p>

            <h3 className="text-2xl font-serif text-foreground mt-12 mb-4"><T>12. Disposiciones finales</T></h3>
            <p><strong><T>12.1. Facultad de modificación.</T></strong> <T>MEXTRIPIA se reserva el derecho de modificar, actualizar o complementar en cualquier momento las presentes Condiciones Generales, ya sea por cambios normativos, por ajustes en sus operaciones internas o por mejoras en la prestación de sus servicios. La versión actualizada será publicada en el sitio web oficial de MEXTRIPIA y sustituirá a la anterior a partir de su fecha de publicación.</T></p>
            <p><strong><T>12.2. Responsabilidad del Usuario.</T></strong> <T>Será responsabilidad exclusiva del Usuario revisar periódicamente las Condiciones Generales vigentes antes de contratar o utilizar cualquier servicio. La contratación posterior a la publicación de modificaciones constituirá aceptación plena, expresa e incondicional de dichas modificaciones.</T></p>
            <p><strong><T>12.3. Carácter vinculante.</T></strong> <T>El Usuario reconoce que estas Condiciones Generales, junto con las condiciones particulares de cada Servicio, constituyen el acuerdo completo, único y vinculante entre las partes, sustituyendo cualquier comunicación, propuesta o entendimiento previo, ya sea verbal o escrito.</T></p>
            <p><strong><T>12.4. Divisibilidad.</T></strong> <T>Si alguna de las disposiciones de estas Condiciones fuese declarada nula, ilegal o inaplicable por autoridad competente, dicha nulidad o inaplicabilidad no afectará la validez y exigibilidad del resto de las cláusulas, las cuales permanecerán vigentes y aplicables en todos sus términos.</T></p>
            <p><strong><T>12.5. No renuncia de derechos.</T></strong> <T>La falta o demora de MEXTRIPIA en ejercer cualquier derecho o facultad derivado de estas Condiciones no constituirá una renuncia al mismo, ni impedirá su ejercicio posterior.</T></p>
            <p><strong><T>12.6. Idioma.</T></strong> <T>En caso de discrepancia entre la versión en español y una eventual traducción a otro idioma de estas Condiciones, prevalecerá siempre la versión en español.</T></p>
            <p><strong><T>12.7. Vigencia.</T></strong> <T>Estas Condiciones Generales estarán vigentes desde su fecha de publicación en el sitio web oficial de MEXTRIPIA y permanecerán aplicables hasta que sean sustituidas por una nueva versión.</T></p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}